FROM bitnami/spark:latest
USER root

# Copia o conteúdo do diretório 'app' do host para o diretório 'app' no contêiner
COPY app /opt/bitnami/python/app

# Instalação do pyspark e py4j
RUN pip install --upgrade pip && \
    /opt/bitnami/python/bin/pip install pyspark