version: "3.7"

services:
  spark-master:
    image: bitnami/spark:latest
    command: |
      bin/spark-class org.apache.spark.deploy.master.Master && \
            /opt/bitnami/python/bin/pip install pyspark py4j
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./app:/app

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./app:/app

  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./app:/app

  python-installer:
    image: python:latest
    command: |
      apt-get update && \
      apt-get install -y python3 && \
      /opt/bitnami/python/bin/pip install pyspark py4j
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    volumes:
      - ./app:/app
